import type { AssetReference } from '@/types';
import { BLEACH_MAP_SRC } from './mapConstants';

/**
 * Asset di Bleach.
 *
 * Copyright: nessuna immagine ufficiale (manga/anime) è inclusa. Le cinque
 * mappe sono disegni ORIGINALI generati da `scripts/bleach-maps.py`
 * (geometria nostra, nessun artwork ufficiale ricalcato) e rilasciati CC0:
 * il mondo rappresentato resta © Tite Kubo / Shueisha.
 */
const NOTES_IT =
  "Ricostruzione originale AniMapVerse generata da scripts/bleach-maps.py: forme disegnate da zero sulla base di ciò che l'opera racconta, nessun artwork ufficiale. Il mondo di Bleach è © Tite Kubo / Shueisha.";
const NOTES_EN =
  'An original AniMapVerse reconstruction generated by scripts/bleach-maps.py: shapes drawn from scratch based on what the series tells, no official artwork. The world of Bleach is © Tite Kubo / Shueisha.';

const map = (id: string, name: string, url: string): AssetReference => ({
  id,
  worldId: 'world-bleach',
  name,
  kind: 'map',
  url,
  source: 'AniMapVerse (scripts/bleach-maps.py)',
  license: 'CC0 (original drawing)',
  author: 'AniMapVerse',
  notes: { it: NOTES_IT, en: NOTES_EN },
});

export const bleachAssets: AssetReference[] = [
  {
    id: 'bl-cover-placeholder',
    worldId: 'world-bleach',
    name: 'Cover placeholder (Bleach)',
    kind: 'placeholder',
    license: 'placeholder/CC0',
    author: 'local',
    notes: {
      it: 'SVG generato localmente, non è materiale ufficiale di Bleach.',
      en: 'Locally generated SVG, not official Bleach material.',
    },
  },
  map('bl-map-three-worlds', 'Bleach · The Three Worlds (original SVG map)', BLEACH_MAP_SRC.world),
  map('bl-map-karakura', 'Bleach · Karakura Town (original SVG map)', BLEACH_MAP_SRC.karakura),
  map('bl-map-seireitei', 'Bleach · Seireitei (original SVG map)', BLEACH_MAP_SRC.seireitei),
  map('bl-map-hueco-mundo', 'Bleach · Hueco Mundo (original SVG map)', BLEACH_MAP_SRC.huecoMundo),
  map('bl-map-reiokyu', 'Bleach · Reiōkyū (original SVG map)', BLEACH_MAP_SRC.reiokyu),
];
