import type { AssetReference } from '@/types';

/**
 * Asset per le mappe ORIGINALI disegnate da AniMapVerse (SVG generati dagli
 * script in `scripts/mapgen/`), usate dove un'opera non ha una mappa
 * ufficiale/utilizzabile per quel luogo. Geometria nostra, nessun artwork
 * ufficiale ricalcato: il disegno è CC0, il mondo rappresentato resta dei
 * suoi autori (`owner`).
 */
export function originalMapAsset(o: {
  id: string;
  worldId: string;
  name: string;
  url: string;
  /** Script che genera il file, es. `scripts/mapgen/naruto.py`. */
  script: string;
  /** Titolare dei diritti dell'opera, es. `Masashi Kishimoto / Shueisha`. */
  owner: string;
}): AssetReference {
  return {
    id: o.id,
    worldId: o.worldId,
    name: `${o.name} (original SVG map)`,
    kind: 'map',
    url: o.url,
    source: `AniMapVerse (${o.script})`,
    license: 'CC0 (original drawing)',
    author: 'AniMapVerse',
    notes: {
      it: `Ricostruzione originale AniMapVerse generata da ${o.script}: forme disegnate da zero sulla base di ciò che l'opera mostra e racconta, nessun artwork ufficiale. Il mondo rappresentato è © ${o.owner}.`,
      en: `An original AniMapVerse reconstruction generated by ${o.script}: shapes drawn from scratch based on what the series shows and tells, no official artwork. The depicted world is © ${o.owner}.`,
    },
  };
}
